create table QUESTION
(
  ID            BIGINT  default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8CFDEFC5_14A6_40BC_B2EA_0E908ABBE7EF)
    primary key,
  TITLE         VARCHAR(50),
  DESCRIPTION   CLOB,
  GMT_CREATE    BIGINT,
  GMT_MODIFIED  BIGINT,
  CREATOR       BIGINT,
  COMMENT_COUNT INTEGER default 0,
  VIEW_COUNT    INTEGER default 0,
  LIKE_COUNT    INTEGER default 0,
  TAG           VARCHAR(256)
);

